more precise status when unable to join remote directory + lower ldapsearch timeout

diff --git a/slapd b/slapd
--- a/slapd
+++ b/slapd
@@ -1203,7 +1203,15 @@ check_sync() {
 		PBASEDN=$( echo "${PROVIDER[$index]}" | sed -e 's/.*searchbase[ \t]*=[ \t]*\([^ \t]\+\).*$/\1/' | sed -e 's/["]//g' | sed -e "s/[']//g" )
 		echo "Checking host ${PHOST}"
 		# Get remote provider contextCSN (one contextCSN per line)
-		CONTEXTCSN=$( ${SLAPD_PATH}/bin/ldapsearch -x -H "${PHOST}" -D "${PBINDDN}" -w "${PBINDPW}" -b "${PBASEDN}" -s base contextCSN -LLL | grep contextCSN | sed -e 's/^contextCSN: //i' )
+		CONTEXTCSN=$( ${SLAPD_PATH}/bin/ldapsearch -x -H "${PHOST}" -D "${PBINDDN}" -w "${PBINDPW}" -b "${PBASEDN}" -o nettimeout=5 -s base contextCSN -LLL 2>/dev/null )
+
+		# Checking status of previous command
+		if [ $? -ne 0 ]; then
+			echo "    ERROR: search on remote host impossible!"
+			let "RES=-1"
+			break
+		fi
+		CONTEXTCSN=$( echo "$CONTEXTCSN" | grep contextCSN | sed -e 's/^contextCSN: //i' )
 
 		# get local contextCSN
 		# TODO: improve this test to check via ldapsearch (need manager account)
@@ -1244,8 +1252,10 @@ check_sync() {
 
 		# return result (OK|KO)
 	done
-	if [[ $RES -eq 0 ]]; then
+	if [[ "$RES" -eq "0" ]]; then
 		message "info" "[OK] Local directory synchronized to every declared provider"
+	elif [[ "$RES" -eq "-1" ]]; then
+		message "error" "[KO] Error while checking synchronization"
 	else
 		message "error" "[KO] Local directory not synchronized to one of its declared providers"
 	fi
